import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import { type Project, calculateProject, TRADE_LABELS } from "@/lib/types";

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: "Helvetica",
    fontSize: 12,
  },
  header: {
    marginBottom: 30,
    borderBottom: "2 solid #2563eb",
    paddingBottom: 15,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#2563eb",
  },
  subtitle: {
    fontSize: 10,
    color: "#666",
    marginTop: 4,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 8,
    backgroundColor: "#f4f4f5",
    padding: 6,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 4,
    borderBottom: "0.5 solid #e5e7eb",
  },
  label: {
    color: "#666",
    flex: 1,
  },
  value: {
    fontWeight: "bold",
    flex: 1,
    textAlign: "right",
  },
  total: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 10,
    marginTop: 10,
    borderTop: "2 solid #2563eb",
  },
  totalLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#2563eb",
  },
  totalValue: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#2563eb",
  },
  notes: {
    marginTop: 20,
    padding: 10,
    backgroundColor: "#f9fafb",
    borderRadius: 4,
    fontSize: 10,
    color: "#666",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 8,
    color: "#999",
  },
});

export function QuotePDF({ project }: { project: Project }) {
  const calc = calculateProject(project);
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Quote</Text>
          <Text style={styles.subtitle}>
            Generated by ProfitScope — {new Date().toLocaleDateString()}
          </Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Client Information</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Client</Text>
            <Text style={styles.value}>{project.client_name}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Address</Text>
            <Text style={styles.value}>{project.client_address}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Trade</Text>
            <Text style={styles.value}>{TRADE_LABELS[project.trade]}</Text>
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Quote Details</Text>
          <View style={styles.row}>
            <Text style={styles.label}>Hourly Rate</Text>
            <Text style={styles.value}>${project.hourly_rate}/hr</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Estimated Hours</Text>
            <Text style={styles.value}>{project.estimated_hours}h</Text>
          </View>
          <View style={styles.total}>
            <Text style={styles.totalLabel}>Quote Total</Text>
            <Text style={styles.totalValue}>
              ${calc.quote_amount.toLocaleString()}
            </Text>
          </View>
        </View>

        {project.notes ? (
          <View style={styles.notes}>
            <Text>Notes: {project.notes}</Text>
          </View>
        ) : null}

        <Text style={styles.footer}>
          ProfitScope — Know what every job pays you.
        </Text>
      </Page>
    </Document>
  );
}
